/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cp.ui2;

import java.awt.event.KeyEvent;
import java.io.ByteArrayInputStream;
import java.io.InputStream;

import cp.fileUtil.MyPrintStream;
import cp.grammer2.MyNewGrammar;

/**
 *
 * @author A550J
 */
public class NewJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	public NewJFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jSplitPane1 = new javax.swing.JSplitPane();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("编译器");
		setBackground(new java.awt.Color(255, 255, 255));
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jSplitPane1.setDividerSize(0);

		jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
		jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		jTextArea1.setEditable(false);
		jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
		jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
		jTextArea1.setRows(5);
		jTextArea1.setText(" 1");
		jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 35, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 323, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)));

		jSplitPane1.setLeftComponent(jPanel2);

		jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
		jTextArea2.setColumns(20);
		jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
		jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
		jTextArea2.setRows(5);
		jTextArea2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
		jTextArea2.setFocusCycleRoot(true);
		jTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextArea2KeyPressed(evt);
			}

			public void keyReleased(java.awt.event.KeyEvent evt) {
				jTextArea2KeyReleased(evt);
			}

			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextArea2KeyTyped(evt);
			}
		});
		jScrollPane2.setViewportView(jTextArea2);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 607, Short.MAX_VALUE)
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
						jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						607, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 323, Short.MAX_VALUE)
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)));

		jSplitPane1.setRightComponent(jPanel3);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 644, Short.MAX_VALUE).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane1)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 325, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)));

		jTabbedPane1.addTab("输入区", jPanel1);

		jButton1.setText("运行");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("清空");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("退出");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jTextArea3.setEditable(false);
		jTextArea3.setBackground(new java.awt.Color(0, 0, 0));
		jTextArea3.setColumns(20);
		jTextArea3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
		jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
		jTextArea3.setRows(5);
		jScrollPane3.setViewportView(jTextArea3);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 644, Short.MAX_VALUE)
				.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 217, Short.MAX_VALUE)
				.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)));

		jTabbedPane2.addTab("输出区", jPanel4);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jTabbedPane1)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton1).addGap(18, 18, 18).addComponent(jButton2).addGap(18, 18, 18)
								.addComponent(jButton3).addGap(5, 5, 5))
				.addComponent(jTabbedPane2));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1).addComponent(jButton2).addComponent(jButton3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		MyPrintStream out = new MyPrintStream(jTextArea3);
		System.setOut(out);

		// System.out.println("input:");
		// jTextArea3.setText("\u8f93\u5165:\n");

		String inputStr = jTextArea2.getText();
		StringBuffer sb = new StringBuffer("\u8f93\u5165:\n" + inputStr + "\n");
		jTextArea3.setText(null);
		System.out.println(sb.toString());
		System.out.println("输出：");
		InputStream in = new ByteArrayInputStream((inputStr+"\r;").getBytes());
		MyNewGrammar parser = new MyNewGrammar(in);
		try {
			parser.Start();
			parser.ReInit(in);
		} catch (Exception e) {
			System.out.println(e.getMessage());
			parser.ReInit(in);
		} catch (Error e) {
			System.out.println("Oops.");
			System.out.println(e.getMessage());
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	int a = 2;

	private void jTextArea2KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextArea2KeyPressed
		int a = jTextArea1.getLineCount();
		int b = jTextArea2.getLineCount();
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			b = b + 1;
			if (b >= a) {
				for (int c = a + 1; c <= b; c++) {
					jTextArea1.append("\r\n" + " " + c);
				}
			}
		}
	}// GEN-LAST:event_jTextArea2KeyPressed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		jTextArea1.setText(" 1");
		jTextArea2.setText(null);
		a = 2;
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		System.exit(0);
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jTextArea2KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextArea2KeyTyped
	}// GEN-LAST:event_jTextArea2KeyTyped

	private void jTextArea2KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextArea2KeyReleased
		int a = jTextArea1.getLineCount();
		int b = jTextArea2.getLineCount();
		if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
			if (b <= a) {
				jTextArea1.setText(" 1");
				if (b == 1) {
				} else {
					for (int c = 2; c <= b; c++) {
						jTextArea1.append("\r\n" + " " + c);

					}
				}
			}
		}
	}// GEN-LAST:event_jTextArea2KeyReleased

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		NewJFrame njf = new NewJFrame();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				njf.setVisible(true);
			}
		});
		njf.jTextArea3.setText("Reading from standard input...\n\u8f93\u5165:");
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	// End of variables declaration//GEN-END:variables
}
