/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package cp.grammer2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int MULTIPLY = 6;
  /** RegularExpression Id. */
  int DIVIDE = 7;
  /** RegularExpression Id. */
  int POW = 8;
  /** RegularExpression Id. */
  int FALSE = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int EEQUALS = 11;
  /** RegularExpression Id. */
  int EQUALS = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int BIGGER = 14;
  /** RegularExpression Id. */
  int SMALLER = 15;
  /** RegularExpression Id. */
  int MORE_EQUAL = 16;
  /** RegularExpression Id. */
  int LESS_EQUAL = 17;
  /** RegularExpression Id. */
  int NOT = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int QUESTION_MARK = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int ELIF = 23;
  /** RegularExpression Id. */
  int PRINT = 24;
  /** RegularExpression Id. */
  int CLASS = 25;
  /** RegularExpression Id. */
  int DEF = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int IN = 29;
  /** RegularExpression Id. */
  int RANGE = 30;
  /** RegularExpression Id. */
  int LEN = 31;
  /** RegularExpression Id. */
  int LPARENT = 32;
  /** RegularExpression Id. */
  int RPARENT = 33;
  /** RegularExpression Id. */
  int LBRACE = 34;
  /** RegularExpression Id. */
  int RBRACE = 35;
  /** RegularExpression Id. */
  int LARRAY = 36;
  /** RegularExpression Id. */
  int RARRAY = 37;
  /** RegularExpression Id. */
  int PREVIOUS = 38;
  /** RegularExpression Id. */
  int DIGITS = 39;
  /** RegularExpression Id. */
  int NUMBER = 40;
  /** RegularExpression Id. */
  int LETTER = 41;
  /** RegularExpression Id. */
  int VARIABLE = 42;
  /** RegularExpression Id. */
  int STRING = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"False\"",
    "\"True\"",
    "\"==\"",
    "\"=\"",
    "\":\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!\"",
    "\",\"",
    "\"?\"",
    "\"if\"",
    "\"else\"",
    "\"elif\"",
    "\"print\"",
    "\"class\"",
    "\"def\"",
    "\"while\"",
    "\"for\"",
    "\"in\"",
    "\"range\"",
    "\"len\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"$\"",
    "<DIGITS>",
    "<NUMBER>",
    "<LETTER>",
    "<VARIABLE>",
    "<STRING>",
    "\";\"",
  };

}
